In [1]:
import pandas as pb
import numpy as np

In [2]:
print(np.__version__)
print(pb.__version__)

2.5.1
3.0.5

In [3]:
# Small dataset
data = {
    "Name": ["Amit", "Riya", "Sohan", "Priya", "Arjun"],
    "Math": [85, 90, 78, 92, 88],
    "Science": [80, 95, 70, 85, 89],
    "English": [75, 88, 82, 91, 77]
}

# Pandas Practice
1.Show the first 3 rows of the dataset.

2.Select only the Math column.

3.Find the average score in Science.

4.Display all students who scored more than 85 in English.

5.Add a new column called Total (sum of Math, Science, English).

6.Sort the dataset by Math scores in descending order.

7.Find the student with the highest Total score.

In [4]:
panda_data = pb.DataFrame(data)

In [5]:
panda_data

    Name  Math  Science  English
0   Amit    85       80       75
1   Riya    90       95       88
2  Sohan    78       70       82
3  Priya    92       85       91
4  Arjun    88       89       77

In [6]:
three_panda_data = panda_data[:3]
three_panda_data

    Name  Math  Science  English
0   Amit    85       80       75
1   Riya    90       95       88
2  Sohan    78       70       82

In [7]:
math_marks_pandas = panda_data['Math']
print("The math data or the math marks :")
math_marks_pandas

The math data or the math marks :

0    85
1    90
2    78
3    92
4    88
Name: Math, dtype: int64

In [8]:
science_marks_pandas = panda_data['Science']
average_sci = science_marks_pandas.mean()
print("The sverage of the science subject is :",average_sci)

The sverage of the science subject is : 83.8

In [9]:
panda_data

    Name  Math  Science  English
0   Amit    85       80       75
1   Riya    90       95       88
2  Sohan    78       70       82
3  Priya    92       85       91
4  Arjun    88       89       77

In [10]:
student_english = panda_data[panda_data['English'] > 85]
print("The student marks gater them 85 are :")
student_english

The student marks gater them 85 are :

    Name  Math  Science  English
1   Riya    90       95       88
3  Priya    92       85       91

In [11]:
total = panda_data[['Math','Science','English']].sum()

print("The total of all marks are :",total)

The total of all marks are : Math       433
Science    419
English    413
dtype: int64

In [12]:
total_mark = panda_data[['Math','English','Science']].sum(axis = 1)
panda_data['Total'] = total_mark
panda_data

    Name  Math  Science  English  Total
0   Amit    85       80       75    240
1   Riya    90       95       88    273
2  Sohan    78       70       82    230
3  Priya    92       85       91    268
4  Arjun    88       89       77    254

In [13]:
math_sort = panda_data.sort_values(by = "Math",ascending= False)
print("The sort data by the math marks :")
math_sort

The sort data by the math marks :

    Name  Math  Science  English  Total
3  Priya    92       85       91    268
1   Riya    90       95       88    273
4  Arjun    88       89       77    254
0   Amit    85       80       75    240
2  Sohan    78       70       82    230

In [14]:
total_mark_again = panda_data[['Math','Science','English']].sum(axis = 1)
hight_marks = total_mark_again.max()
top_student = panda_data[panda_data['Total'] == hight_marks]
print("The top student is :")
top_student

The top student is :

   Name  Math  Science  English  Total
1  Riya    90       95       88    273

# 🔹 NumPy Practice
1.Convert the Math column into a NumPy array.

2.Find the maximum and minimum Math scores.

3.Calculate the mean of the Science scores using NumPy.

4.Create a NumPy array of all English scores and add 5 bonus marks to each.

5.Use slicing to get the first 3 Math scores from the array.

6.Find the standard deviation of Science scores.

In [40]:
data

{'Name': ['Amit', 'Riya', 'Sohan', 'Priya', 'Arjun'],
 'Math': [85, 90, 78, 92, 88],
 'Science': [80, 95, 70, 85, 89],
 'English': [75, 88, 82, 91, 77]}

In [16]:
data_numpy = np.array(data)
print("The full data into numpy array :")
data_numpy

The full data into numpy array :

array({'Name': ['Amit', 'Riya', 'Sohan', 'Priya', 'Arjun'], 'Math': [85, 90, 78, 92, 88], 'Science': [80, 95, 70, 85, 89], 'English': [75, 88, 82, 91, 77]},
      dtype=object)

In [20]:
#cunvat the math colon into a numpy array 
math_numpy = np.array(data['Math'])

In [24]:
print("The numpy data fo the math culon is :")
math_numpy

The numpy data fo the math culon is :

array([85, 90, 78, 92, 88])

In [25]:
#find the maximum number of math marks 
print("The mazimum number of the math is :",math_data.max())

The mazimum number of the math is : 92

In [26]:
science_marks = np.array(data['Science'])
science_marks

array([80, 95, 70, 85, 89])

In [27]:
# calculate the mean of science marks 
average_science_marks = science_marks.mean()
print("The average (mean) of the science marks is :",average_science_marks)

The average (mean) of the science marks is : 83.8

In [28]:
English_marks = np.array(data['English'])
English_marks

array([75, 88, 82, 91, 77])

In [34]:
bonas_marks_eng = English_marks + 5
print("The origimal marks is :",English_marks)
print("The marks with bonass is :",bonas_marks_eng)

The origimal marks is : [75 88 82 91 77]
The marks with bonass is : [80 93 87 96 82]

In [35]:
first_three_math = math_numpy[:3]
print("The data of the first three of math is :",first_three_math)

The data of the first three of math is : [85 90 78]

In [39]:
#stand divisition of the science subject 
std_div_science = np.std(science_marks)
print("The standard division of science marks is :",round(std_div_science,2))

The standard division of science marks is : 8.47

In [41]:
science_marks

array([80, 95, 70, 85, 89])

In [42]:
data

{'Name': ['Amit', 'Riya', 'Sohan', 'Priya', 'Arjun'],
 'Math': [85, 90, 78, 92, 88],
 'Science': [80, 95, 70, 85, 89],
 'English': [75, 88, 82, 91, 77]}

# All Don Thanks