In [1]:
import numpy as np 
import pandas as pd

In [2]:
main_data = pd.read_csv('Employee.csv')
main_data

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1
...,...,...,...,...,...,...,...,...,...
4648,Bachelors,2013,Bangalore,3,26,Female,No,4,0
4649,Masters,2013,Pune,2,37,Male,No,2,1
4650,Masters,2018,New Delhi,3,27,Male,No,5,1
4651,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0
4652,Bachelors,2015,Bangalore,3,33,Male,Yes,4,0

In [3]:
main_data[30:39]

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
30,PHD,2013,New Delhi,3,25,Male,No,3,0
31,Bachelors,2014,Bangalore,3,23,Male,No,1,0
32,Bachelors,2018,Bangalore,3,26,Male,No,4,1
33,Bachelors,2016,Bangalore,3,40,Male,No,5,0
34,Bachelors,2017,Pune,2,37,Female,No,0,1
35,Bachelors,2014,Bangalore,1,30,Female,No,3,0
36,Bachelors,2012,New Delhi,3,29,Male,No,3,0
37,Bachelors,2018,New Delhi,2,34,Female,No,0,1
38,Bachelors,2017,Pune,2,29,Female,No,2,1

In [30]:
print(main_data.head(5))      # View first 5 rows
print(main_data.tail(5))# View last 5 rows
print(main_data.info())        # Memory usage, data types, non-null counts
print(main_data.describe())    # Summary statistics for numerical columns
print(main_data.shape)        # Tuple representing (rows, columns)
print(main_data.columns)       # List column names
print(main_data.index)         # Get row labels

   Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0  Bachelors         2017  Bangalore            3   34    Male          No
1  Bachelors         2013       Pune            1   28  Female          No
2  Bachelors         2014  New Delhi            3   38  Female          No
3    Masters         2016  Bangalore            3   27    Male          No
4    Masters         2017       Pune            3   24    Male         Yes

   Experience  LeaveOrNot Joning_Status Joining Rate
0           0           0           New         High
1           3           1           Old          Mid
2           2           0           Old          Mid
3           5           1           New          Low
4           2           1           New         High
      Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
4648  Bachelors         2013  Bangalore            3   26  Female          No
4649    Masters         2013       Pune            2   37    Male          No
4650    Masters         2018  New Delhi            3   27    Male          No
4651  Bachelors         2012  Bangalore            3   30    Male         Yes
4652  Bachelors         2015  Bangalore            3   33    Male         Yes

      Experience  LeaveOrNot Joning_Status Joining Rate
4648           4           0           Old          Mid
4649           2           1           Old          Mid
4650           5           1           New          Low
4651           2           0           Old          Low
4652           4           0           Mid          Mid
<class 'pandas.DataFrame'>
RangeIndex: 4653 entries, 0 to 4652
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Education      4653 non-null   str
 1   JoiningYear    4653 non-null   int64
 2   City           4653 non-null   str
 3   PaymentTier    4653 non-null   int64
 4   Age            4653 non-null   int64
 5   Gender         4653 non-null   str
 6   EverBenched    4653 non-null   str
 7   Experience     4653 non-null   int64
 8   LeaveOrNot     4653 non-null   int64
 9   Joning_Status  4653 non-null   str
 10  Joining Rate   4653 non-null   str
dtypes: int64(5), str(6)
memory usage: 400.0 KB
None
       JoiningYear  PaymentTier          Age   Experience   LeaveOrNot
count  4653.000000  4653.000000  4653.000000  4653.000000  4653.000000
mean   2015.062970     2.698259    29.393295     2.905652     0.343864
std       1.863377     0.561435     4.826087     1.558240     0.475047
min    2012.000000     1.000000    22.000000     0.000000     0.000000
25%    2013.000000     3.000000    26.000000     2.000000     0.000000
50%    2015.000000     3.000000    28.000000     3.000000     0.000000
75%    2017.000000     3.000000    32.000000     4.000000     1.000000
max    2018.000000     3.000000    41.000000     7.000000     1.000000
(4653, 11)
Index(['Education', 'JoiningYear', 'City', 'PaymentTier', 'Age', 'Gender',
       'EverBenched', 'Experience', 'LeaveOrNot', 'Joning_Status',
       'Joining Rate'],
      dtype='str')
RangeIndex(start=0, stop=4653, step=1)

In [28]:
main_data.shape

(4653, 11)

In [4]:
main_data.head().transpose()

                                   0          1          2          3        4
Education                  Bachelors  Bachelors  Bachelors    Masters  Masters
JoiningYear                     2017       2013       2014       2016     2017
City                       Bangalore       Pune  New Delhi  Bangalore     Pune
PaymentTier                        3          1          3          3        3
Age                               34         28         38         27       24
Gender                          Male     Female     Female       Male     Male
EverBenched                       No         No         No         No      Yes
ExperienceInCurrentDomain          0          3          2          5        2
LeaveOrNot                         0          1          0          1        1

In [5]:
main_data[0:7]

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1
5,Bachelors,2016,Bangalore,3,22,Male,No,0,0
6,Bachelors,2015,New Delhi,3,38,Male,No,0,0

In [6]:
main_data[:9]

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1
5,Bachelors,2016,Bangalore,3,22,Male,No,0,0
6,Bachelors,2015,New Delhi,3,38,Male,No,0,0
7,Bachelors,2016,Bangalore,3,34,Female,No,2,1
8,Bachelors,2016,Pune,3,23,Male,No,1,0

In [7]:
main_data[-5:] #that starts with the end and give the outpun in revers order.

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
4648,Bachelors,2013,Bangalore,3,26,Female,No,4,0
4649,Masters,2013,Pune,2,37,Male,No,2,1
4650,Masters,2018,New Delhi,3,27,Male,No,5,1
4651,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0
4652,Bachelors,2015,Bangalore,3,33,Male,Yes,4,0

In [8]:
print("The shape of the employ data is :",main_data.shape)

The shape of the employ data is : (4653, 9)

In [9]:
print("The data informaction is :")
print(main_data.info())

The data informaction is :
<class 'pandas.DataFrame'>
RangeIndex: 4653 entries, 0 to 4652
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Education                  4653 non-null   str
 1   JoiningYear                4653 non-null   int64
 2   City                       4653 non-null   str
 3   PaymentTier                4653 non-null   int64
 4   Age                        4653 non-null   int64
 5   Gender                     4653 non-null   str
 6   EverBenched                4653 non-null   str
 7   ExperienceInCurrentDomain  4653 non-null   int64
 8   LeaveOrNot                 4653 non-null   int64
dtypes: int64(5), str(4)
memory usage: 327.3 KB
None

In [10]:
print("The name of all colomes are :")
print(main_data.columns)

The name of all colomes are :
Index(['Education', 'JoiningYear', 'City', 'PaymentTier', 'Age', 'Gender',
       'EverBenched', 'ExperienceInCurrentDomain', 'LeaveOrNot'],
      dtype='str')

In [11]:
# THE COUNT OF THE BACTHOLAR EDUCATION EMPLOYS IN THE DATA 
print("The count of the Bachelors degry employ are :")
print(main_data.value_counts(main_data['Education'] == 'Bachelors'))

The count of the Bachelors degry employ are :
Education
True     3601
False    1052
Name: count, dtype: int64

In [12]:
print("The count of null valuse in teh columns are :")
for c in main_data.columns:
    print(c ,main_data[c].isna().sum())

The count of null valuse in teh columns are :
Education 0
JoiningYear 0
City 0
PaymentTier 0
Age 0
Gender 0
EverBenched 0
ExperienceInCurrentDomain 0
LeaveOrNot 0

In [13]:
main_data.describe()

,JoiningYear,PaymentTier,Age,ExperienceInCurrentDomain,LeaveOrNot
count,4653.000000,4653.000000,4653.000000,4653.000000,4653.000000
mean,2015.062970,2.698259,29.393295,2.905652,0.343864
std,1.863377,0.561435,4.826087,1.558240,0.475047
min,2012.000000,1.000000,22.000000,0.000000,0.000000
25%,2013.000000,3.000000,26.000000,2.000000,0.000000
50%,2015.000000,3.000000,28.000000,3.000000,0.000000
75%,2017.000000,3.000000,32.000000,4.000000,1.000000
max,2018.000000,3.000000,41.000000,7.000000,1.000000

In [14]:
main_data.head()

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1

In [15]:
main_data.tail()

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
4648,Bachelors,2013,Bangalore,3,26,Female,No,4,0
4649,Masters,2013,Pune,2,37,Male,No,2,1
4650,Masters,2018,New Delhi,3,27,Male,No,5,1
4651,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0
4652,Bachelors,2015,Bangalore,3,33,Male,Yes,4,0

In [16]:
main_data.dtypes

Education                      str
JoiningYear                  int64
City                           str
PaymentTier                  int64
Age                          int64
Gender                         str
EverBenched                    str
ExperienceInCurrentDomain    int64
LeaveOrNot                   int64
dtype: object

In [17]:
def join_after(date):
    if date > 2015:
        return 'New'
    elif date < 2015:
        return 'Old'
    else:
       return 'Mid'

In [18]:
print("The new joiners years :",main_data['JoiningYear'].max())
print("The older joiners year :",main_data['JoiningYear'].min())

The new joiners years : 2018
The older joiners year : 2012

In [19]:
main_data['Joning_Status'] = main_data['JoiningYear'].apply(join_after)
main_data.head()

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot,Joning_Status
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0,New
1,Bachelors,2013,Pune,1,28,Female,No,3,1,Old
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0,Old
3,Masters,2016,Bangalore,3,27,Male,No,5,1,New
4,Masters,2017,Pune,3,24,Male,Yes,2,1,New

In [20]:
n = main_data.groupby('Joning_Status')['Age'].mean()
n

Joning_Status
Mid    29.476312
New    29.472500
Old    29.274038
Name: Age, dtype: float64

In [21]:
m = main_data.groupby('Joning_Status')['Age'].mean().reset_index()
m

  Joning_Status        Age
0           Mid  29.476312
1           New  29.472500
2           Old  29.274038

In [22]:
main_data.value_counts()

Education  JoiningYear  City       PaymentTier  Age  Gender  EverBenched  ExperienceInCurrentDomain  LeaveOrNot  Joning_Status
Bachelors  2013         Bangalore  3            26   Male    No           4                          0           Old              32
           2016         Bangalore  3            26   Male    No           4                          0           New              28
           2012         Bangalore  3            26   Male    No           4                          0           Old              26
           2014         Bangalore  3            25   Male    No           3                          0           Old              24
                                                26   Male    No           4                          0           Old              24
                                                                                                                                  ..
Masters    2017         Pune       2            31   Female  No           2                          0           New               1
Bachelors  2016         Pune       3            30   Male    No           2                          0           New               1
Masters    2013         Pune       2            37   Male    No           2                          1           Old               1
           2018         New Delhi  3            27   Male    No           5                          1           New               1
Bachelors  2012         Bangalore  3            30   Male    Yes          2                          0           Old               1
Name: count, Length: 2764, dtype: int64

In [23]:
joyinig_year_data = main_data.value_counts(main_data['JoiningYear'],ascending=True)
joyinig_year_data.reset_index()

   JoiningYear  count
0         2018    367
1         2012    504
2         2016    525
3         2013    669
4         2014    699
5         2015    781
6         2017   1108

In [24]:
def joiningRate(date):
    if date == 2018 or date == 2012 or date == 2016:
        return "Low"
    elif 2013 <= date <= 2015:
        return "Mid"
    else:
        return "High"

In [25]:
main_data['Joining Rate']=main_data['JoiningYear'].apply(joiningRate)
main_data.head

<bound method NDFrame.head of       Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0     Bachelors         2017  Bangalore            3   34    Male          No
1     Bachelors         2013       Pune            1   28  Female          No
2     Bachelors         2014  New Delhi            3   38  Female          No
3       Masters         2016  Bangalore            3   27    Male          No
4       Masters         2017       Pune            3   24    Male         Yes
...         ...          ...        ...          ...  ...     ...         ...
4648  Bachelors         2013  Bangalore            3   26  Female          No
4649    Masters         2013       Pune            2   37    Male          No
4650    Masters         2018  New Delhi            3   27    Male          No
4651  Bachelors         2012  Bangalore            3   30    Male         Yes
4652  Bachelors         2015  Bangalore            3   33    Male         Yes

      ExperienceInCurrentDomain  LeaveOrNot Joning_Status Joining Rate
0                             0           0           New         High
1                             3           1           Old          Mid
2                             2           0           Old          Mid
3                             5           1           New          Low
4                             2           1           New         High
...                         ...         ...           ...          ...
4648                          4           0           Old          Mid
4649                          2           1           Old          Mid
4650                          5           1           New          Low
4651                          2           0           Old          Low
4652                          4           0           Mid          Mid

[4653 rows x 11 columns]>

In [26]:
main_data.rename(columns={'ExperienceInCurrentDomain':'Experience'},inplace=True)

In [27]:
main_data.head()

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,Experience,LeaveOrNot,Joning_Status,Joining Rate
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0,New,High
1,Bachelors,2013,Pune,1,28,Female,No,3,1,Old,Mid
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0,Old,Mid
3,Masters,2016,Bangalore,3,27,Male,No,5,1,New,Low
4,Masters,2017,Pune,3,24,Male,Yes,2,1,New,High