In [1]:
data = {
    "Employee": ["Amit", "Riya", "Sohan", "Priya", "Arjun", "Neha", "Karan", "Meera"],
    "Department": ["HR", "IT", "Finance", "IT", "Finance", "HR", "IT", "Finance"],
    "Salary": [45000, 60000, 52000, 75000, 58000, 47000, 62000, 54000],
    "Experience": [2, 5, 3, 7, 4, 2, 6, 3],
    "Performance": [80, 92, 75, 95, 88, 70, 90, 85]
}

In [2]:
attendance_data = {
    "Employee": ["Amit", "Riya", "Sohan", "Priya", "Arjun", "Neha", "Karan", "Meera"],
    "Days_Present": [22, 25, 20, 27, 24, 21, 26, 23],
    "Days_Absent": [3, 1, 5, 0, 2, 4, 1, 2],
    "Leave_Days": [1, 0, 2, 0, 1, 2, 0, 1]
}

In [3]:
import numpy as np
import pandas as pd
import random

# Pandas Tasks
1.Show all employees who work in the IT department.

2.Find the average salary of Finance department employees.

3.Add a new column called Bonus = 10% of Salary.

4.Sort employees by Performance in descending order.

5.Group employees by Department and calculate the average Experience.

6.Find the employee with the highest salary.

In [4]:
pandas_data = pd.DataFrame(data)
pandas_data

  Employee Department  Salary  Experience  Performance
0     Amit         HR   45000           2           80
1     Riya         IT   60000           5           92
2    Sohan    Finance   52000           3           75
3    Priya         IT   75000           7           95
4    Arjun    Finance   58000           4           88
5     Neha         HR   47000           2           70
6    Karan         IT   62000           6           90
7    Meera    Finance   54000           3           85

In [5]:
# show all the employ that are working in IT department 
IT_department =pandas_data[pandas_data['Department'] == 'IT']
print("The IT employs only :")
IT_department

The IT employs only :

  Employee Department  Salary  Experience  Performance
1     Riya         IT   60000           5           92
3    Priya         IT   75000           7           95
6    Karan         IT   62000           6           90

In [6]:
# Find the average salary of Finance department employees
finans_department = pandas_data[pandas_data['Department'] == 'Finance']
finans_department_salary = finans_department['Salary']
average_salary_Fin = finans_department_salary.mean()
print("The average salary of the finans department is :",round(average_salary_Fin,2))

The average salary of the finans department is : 54666.67

In [7]:
# Add a new column called Bonus = 10% of Salary
pandas_data['Bonus'] = pandas_data['Salary']/10
pandas_data

  Employee Department  Salary  Experience  Performance   Bonus
0     Amit         HR   45000           2           80  4500.0
1     Riya         IT   60000           5           92  6000.0
2    Sohan    Finance   52000           3           75  5200.0
3    Priya         IT   75000           7           95  7500.0
4    Arjun    Finance   58000           4           88  5800.0
5     Neha         HR   47000           2           70  4700.0
6    Karan         IT   62000           6           90  6200.0
7    Meera    Finance   54000           3           85  5400.0

In [8]:
# Sort employees by Performance in descending order
sort_by_perfomence = pandas_data.sort_values(by='Performance',ascending= False)
print("The sorted employee list based on Performance is :")
sort_by_perfomence

The sorted employee list based on Performance is :

  Employee Department  Salary  Experience  Performance   Bonus
3    Priya         IT   75000           7           95  7500.0
1     Riya         IT   60000           5           92  6000.0
6    Karan         IT   62000           6           90  6200.0
4    Arjun    Finance   58000           4           88  5800.0
7    Meera    Finance   54000           3           85  5400.0
0     Amit         HR   45000           2           80  4500.0
2    Sohan    Finance   52000           3           75  5200.0
5     Neha         HR   47000           2           70  4700.0

In [9]:
# Group employees by Department and calculate the average Experience
data_by_department = pandas_data.groupby('Department')['Experience'].mean()
print("The average of the department expreance is :\n ",data_by_department)

The average of the department expreance is :
  Department
Finance    3.333333
HR         2.000000
IT         6.000000
Name: Experience, dtype: float64

In [10]:
data_by_department.reset_index()

  Department  Experience
0    Finance    3.333333
1         HR    2.000000
2         IT    6.000000

In [11]:
pandas_data

  Employee Department  Salary  Experience  Performance   Bonus
0     Amit         HR   45000           2           80  4500.0
1     Riya         IT   60000           5           92  6000.0
2    Sohan    Finance   52000           3           75  5200.0
3    Priya         IT   75000           7           95  7500.0
4    Arjun    Finance   58000           4           88  5800.0
5     Neha         HR   47000           2           70  4700.0
6    Karan         IT   62000           6           90  6200.0
7    Meera    Finance   54000           3           85  5400.0

In [15]:
employ_attendence = pd.DataFrame(attendance_data)
employ_attendence

  Employee  Days_Present  Days_Absent  Leave_Days
0     Amit            22            3           1
1     Riya            25            1           0
2    Sohan            20            5           2
3    Priya            27            0           0
4    Arjun            24            2           1
5     Neha            21            4           2
6    Karan            26            1           0
7    Meera            23            2           1

In [22]:
mearge_data2 = pd.merge(pandas_data,employ_attendence,on='Employee',how='inner')
print("The data outer add :\n",mearge_data2)

The data outer add :
   Employee Department  Salary  Experience  Performance   Bonus  Days_Present  \
0     Amit         HR   45000           2           80  4500.0            22
1     Riya         IT   60000           5           92  6000.0            25
2    Sohan    Finance   52000           3           75  5200.0            20
3    Priya         IT   75000           7           95  7500.0            27
4    Arjun    Finance   58000           4           88  5800.0            24
5     Neha         HR   47000           2           70  4700.0            21
6    Karan         IT   62000           6           90  6200.0            26
7    Meera    Finance   54000           3           85  5400.0            23

   Days_Absent  Leave_Days
0            3           1
1            1           0
2            5           2
3            0           0
4            2           1
5            4           2
6            1           0
7            2           1

# NumPy Tasks
1.Convert the Salary column into a NumPy array and calculate the mean.

2.Find the maximum and minimum Performance scores.

3.Calculate the variance of Experience.

4.Add ₹5000 to every salary using NumPy broadcasting.

5.Use slicing to get the first 4 salaries.

6.Find the correlation between Salary and Performance using NumPy.