In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("ai_ds_job_salaries_2026.csv")
data

,job_title,experience_level,employment_type,company_size,company_location,employee_residence,industry,remote_ratio,years_experience,education_level,...,ai_tools_hours_per_week,salary_currency,salary_usd,equity_offered_pct,bonus_pct,job_satisfaction_score,interviews_to_offer,switched_jobs_last_year,upskilling_hours_per_month,fears_ai_automation_score
0,Data Analyst,Lead,Part-time,S,IN,AU,Finance,0,14.4,Bachelors,...,12.5,INR,23844,0.505,11.6,5.5,8,True,2.2,7.4
1,Research Scientist,Senior,Full-time,L,US,US,Retail,50,7.6,Masters,...,2.1,USD,170132,0.054,2.9,7.0,3,False,8.2,5.3
2,Machine Learning Engineer,Entry,Full-time,M,US,US,Government,0,0.0,Bootcamp,...,5.1,USD,83059,0.191,7.5,5.9,1,False,2.8,6.8
3,Data Engineer,Senior,Full-time,M,BR,IN,Government,100,9.7,Masters,...,2.0,BRL,29531,0.102,9.3,5.6,5,False,7.8,5.0
4,Data Engineer,Mid,Full-time,M,US,US,Education,0,3.2,Bachelors,...,4.0,USD,70105,0.064,10.6,4.6,4,False,9.1,5.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Data Analyst,Mid,Full-time,M,PL,PL,Finance,50,9.3,Masters,...,1.5,PLN,38810,0.182,12.0,7.3,2,False,7.8,4.8
4996,Machine Learning Engineer,Lead,Full-time,M,ES,ES,Technology,0,13.3,Self-taught,...,2.6,EUR,123368,0.000,11.0,5.5,7,False,4.0,1.3
4997,Data Science Manager,Senior,Full-time,M,PL,PL,Technology,50,8.1,Bachelors,...,9.7,PLN,86123,0.078,13.3,7.0,6,True,19.2,2.7
4998,Research Scientist,Senior,Freelance,M,PL,PL,Technology,0,12.9,Bachelors,...,10.7,PLN,76001,0.122,10.1,6.0,4,True,10.8,1.5
4999,Business Intelligence Analyst,Entry,Contract,M,US,US,Government,0,2.1,Masters,...,10.4,USD,49321,0.022,4.8,6.6,3,False,6.9,6.1

In [3]:
data.head()

,job_title,experience_level,employment_type,company_size,company_location,employee_residence,industry,remote_ratio,years_experience,education_level,...,ai_tools_hours_per_week,salary_currency,salary_usd,equity_offered_pct,bonus_pct,job_satisfaction_score,interviews_to_offer,switched_jobs_last_year,upskilling_hours_per_month,fears_ai_automation_score
0,Data Analyst,Lead,Part-time,S,IN,AU,Finance,0,14.4,Bachelors,...,12.5,INR,23844,0.505,11.6,5.5,8,True,2.2,7.4
1,Research Scientist,Senior,Full-time,L,US,US,Retail,50,7.6,Masters,...,2.1,USD,170132,0.054,2.9,7.0,3,False,8.2,5.3
2,Machine Learning Engineer,Entry,Full-time,M,US,US,Government,0,0.0,Bootcamp,...,5.1,USD,83059,0.191,7.5,5.9,1,False,2.8,6.8
3,Data Engineer,Senior,Full-time,M,BR,IN,Government,100,9.7,Masters,...,2.0,BRL,29531,0.102,9.3,5.6,5,False,7.8,5.0
4,Data Engineer,Mid,Full-time,M,US,US,Education,0,3.2,Bachelors,...,4.0,USD,70105,0.064,10.6,4.6,4,False,9.1,5.1

In [4]:
print("The shape of the given data is :",data.shape)

The shape of the given data is : (5000, 27)

In [5]:
print("The data type of the each attrubets is :\n",data.dtypes)

The data type of the each attrubets is :
 job_title                         str
experience_level                  str
employment_type                   str
company_size                      str
company_location                  str
employee_residence                str
industry                          str
remote_ratio                    int64
years_experience              float64
education_level                   str
primary_language                  str
has_ml_in_title                  bool
manages_people                   bool
team_size                       int64
certifications_count            int64
weekly_hours                  float64
uses_ai_tools_daily              bool
ai_tools_hours_per_week       float64
salary_currency                   str
salary_usd                      int64
equity_offered_pct            float64
bonus_pct                     float64
job_satisfaction_score        float64
interviews_to_offer             int64
switched_jobs_last_year          bool
upskilling_hours_per_month    float64
fears_ai_automation_score     float64
dtype: object

In [6]:
# to check how many null values are in the database each colome .
print("The sum of all null valus of each colome :")
print(data.isnull().sum())

The sum of all null valus of each colome :
job_title                     0
experience_level              0
employment_type               0
company_size                  0
company_location              0
employee_residence            0
industry                      0
remote_ratio                  0
years_experience              0
education_level               0
primary_language              0
has_ml_in_title               0
manages_people                0
team_size                     0
certifications_count          0
weekly_hours                  0
uses_ai_tools_daily           0
ai_tools_hours_per_week       0
salary_currency               0
salary_usd                    0
equity_offered_pct            0
bonus_pct                     0
job_satisfaction_score        0
interviews_to_offer           0
switched_jobs_last_year       0
upskilling_hours_per_month    0
fears_ai_automation_score     0
dtype: int64

In [7]:
data.tail()

,job_title,experience_level,employment_type,company_size,company_location,employee_residence,industry,remote_ratio,years_experience,education_level,...,ai_tools_hours_per_week,salary_currency,salary_usd,equity_offered_pct,bonus_pct,job_satisfaction_score,interviews_to_offer,switched_jobs_last_year,upskilling_hours_per_month,fears_ai_automation_score
4995,Data Analyst,Mid,Full-time,M,PL,PL,Finance,50,9.3,Masters,...,1.5,PLN,38810,0.182,12.0,7.3,2,False,7.8,4.8
4996,Machine Learning Engineer,Lead,Full-time,M,ES,ES,Technology,0,13.3,Self-taught,...,2.6,EUR,123368,0.000,11.0,5.5,7,False,4.0,1.3
4997,Data Science Manager,Senior,Full-time,M,PL,PL,Technology,50,8.1,Bachelors,...,9.7,PLN,86123,0.078,13.3,7.0,6,True,19.2,2.7
4998,Research Scientist,Senior,Freelance,M,PL,PL,Technology,0,12.9,Bachelors,...,10.7,PLN,76001,0.122,10.1,6.0,4,True,10.8,1.5
4999,Business Intelligence Analyst,Entry,Contract,M,US,US,Government,0,2.1,Masters,...,10.4,USD,49321,0.022,4.8,6.6,3,False,6.9,6.1

In [8]:
data.columns

Index(['job_title', 'experience_level', 'employment_type', 'company_size',
       'company_location', 'employee_residence', 'industry', 'remote_ratio',
       'years_experience', 'education_level', 'primary_language',
       'has_ml_in_title', 'manages_people', 'team_size',
       'certifications_count', 'weekly_hours', 'uses_ai_tools_daily',
       'ai_tools_hours_per_week', 'salary_currency', 'salary_usd',
       'equity_offered_pct', 'bonus_pct', 'job_satisfaction_score',
       'interviews_to_offer', 'switched_jobs_last_year',
       'upskilling_hours_per_month', 'fears_ai_automation_score'],
      dtype='str')

In [9]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 27 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   job_title                   5000 non-null   str
 1   experience_level            5000 non-null   str
 2   employment_type             5000 non-null   str
 3   company_size                5000 non-null   str
 4   company_location            5000 non-null   str
 5   employee_residence          5000 non-null   str
 6   industry                    5000 non-null   str
 7   remote_ratio                5000 non-null   int64
 8   years_experience            5000 non-null   float64
 9   education_level             5000 non-null   str
 10  primary_language            5000 non-null   str
 11  has_ml_in_title             5000 non-null   bool
 12  manages_people              5000 non-null   bool
 13  team_size                   5000 non-null   int64
 14  certifications_count        5000 non-null   int64
 15  weekly_hours                5000 non-null   float64
 16  uses_ai_tools_daily         5000 non-null   bool
 17  ai_tools_hours_per_week     5000 non-null   float64
 18  salary_currency             5000 non-null   str
 19  salary_usd                  5000 non-null   int64
 20  equity_offered_pct          5000 non-null   float64
 21  bonus_pct                   5000 non-null   float64
 22  job_satisfaction_score      5000 non-null   float64
 23  interviews_to_offer         5000 non-null   int64
 24  switched_jobs_last_year     5000 non-null   bool
 25  upskilling_hours_per_month  5000 non-null   float64
 26  fears_ai_automation_score   5000 non-null   float64
dtypes: bool(4), float64(8), int64(5), str(10)
memory usage: 918.1 KB

In [10]:
data.describe()

,remote_ratio,years_experience,team_size,certifications_count,weekly_hours,ai_tools_hours_per_week,salary_usd,equity_offered_pct,bonus_pct,job_satisfaction_score,interviews_to_offer,upskilling_hours_per_month,fears_ai_automation_score
count,5000.00000,5000.000000,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,43.08000,8.361440,7.93620,1.820400,44.345400,8.437400,98605.406200,0.139020,10.802720,6.685320,5.230800,8.680740,4.846080
std,41.45428,4.820808,2.64793,1.344212,6.142761,5.503637,55369.310473,0.184243,5.152959,1.364302,2.412695,4.422549,1.725924
min,0.00000,0.000000,1.00000,0.000000,24.400000,0.000000,12000.000000,0.000000,0.000000,1.100000,1.000000,0.000000,1.000000
25%,0.00000,4.800000,6.00000,1.000000,40.100000,3.300000,55592.750000,0.017000,7.100000,5.800000,3.000000,5.600000,3.700000
50%,50.00000,8.100000,8.00000,2.000000,44.400000,8.500000,90572.000000,0.072000,10.600000,6.700000,5.000000,8.700000,4.800000
75%,100.00000,11.500000,10.00000,3.000000,48.500000,12.625000,129657.750000,0.175000,14.200000,7.600000,7.000000,11.700000,6.000000
max,100.00000,23.700000,19.00000,8.000000,67.300000,25.200000,372347.000000,1.264000,30.800000,10.000000,16.000000,26.200000,10.000000

In [11]:
# to see the count of the industrys 
industry_data = data.value_counts(data['industry'])
print("The count of the industrys are :",industry_data.count())

The count of the industrys are : 10

In [12]:
# to see the names of the industrys 
industry_name = data['industry'].unique()
industry_name

<StringArray>
[      'Finance',        'Retail',    'Government',     'Education',
    'Technology',    'Healthcare',    'Consulting',         'Media',
 'Manufacturing',        'Energy']
Length: 10, dtype: str

In [13]:
# sort the industry names in assinding order 

# Get unique values as a Series
industries = pd.Series(data['industry'].unique())

# Sort ascending
industries.sort_values()

6       Consulting
3        Education
9           Energy
0          Finance
2       Government
5       Healthcare
8    Manufacturing
7            Media
1           Retail
4       Technology
dtype: str

In [14]:
# TYPE OF EXPRIENCE LEVEL HAVE IN THE DATA BASE
experience_level_data = data.value_counts(data['experience_level'])
print("The count of each experience level employs are :",experience_level_data)

The count of each experience level employs are : experience_level
Mid          1613
Senior       1520
Entry         985
Lead          656
Executive     226
Name: count, dtype: int64

In [15]:
# COUNT OF THE JOB TITEL / NAME HAVE IN THE DATA DASE 
jod_title_data = data.value_counts(data['job_title'])
jod_title_data

job_title
Data Scientist                   709
Data Engineer                    682
Data Analyst                     627
Machine Learning Engineer        593
AI Engineer                      506
Analytics Engineer               317
MLOps Engineer                   306
Business Intelligence Analyst    293
Research Scientist               269
LLM Engineer                     242
Data Science Manager             238
Computer Vision Engineer         218
Name: count, dtype: int64

In [16]:
# count the number of industery that have data engineer job titel
industry_count_job_title = data[data['job_title'] == 'Data Engineer']['industry']
print("The industry count of data engineer post are :",industry_count_job_title.value_counts())

The industry count of data engineer post are : industry
Technology       202
Finance          116
Healthcare        72
Retail            67
Consulting        67
Government        40
Manufacturing     37
Media             35
Education         31
Energy            15
Name: count, dtype: int64

In [17]:
# show the type of employ works and there count 

employ_type = data.value_counts(data['employment_type'])
employ_type

employment_type
Full-time    4159
Contract      418
Freelance     212
Part-time     211
Name: count, dtype: int64

In [18]:
# print the salary 
salary_employ = data['salary_usd'].max()
print("The salary of all employ are :")
print(salary_employ)

The salary of all employ are :
372347

In [19]:
#print the highest salary employ ,the details we need are - industry,salary,years_experience,interviews_to_offer,certifications_count
highest_salary = data.loc[data['salary_usd'].idxmax(),
                          ['industry','salary_usd','years_experience',
                           'interviews_to_offer','certifications_count']]
print(highest_salary)

industry                Technology
salary_usd                  372347
years_experience               9.2
interviews_to_offer              1
certifications_count             0
Name: 2935, dtype: object

In [20]:
data.columns

Index(['job_title', 'experience_level', 'employment_type', 'company_size',
       'company_location', 'employee_residence', 'industry', 'remote_ratio',
       'years_experience', 'education_level', 'primary_language',
       'has_ml_in_title', 'manages_people', 'team_size',
       'certifications_count', 'weekly_hours', 'uses_ai_tools_daily',
       'ai_tools_hours_per_week', 'salary_currency', 'salary_usd',
       'equity_offered_pct', 'bonus_pct', 'job_satisfaction_score',
       'interviews_to_offer', 'switched_jobs_last_year',
       'upskilling_hours_per_month', 'fears_ai_automation_score'],
      dtype='str')

In [21]:
# print the hight salary offerd in every industry (each industry hight salary employ offerd)
print("hello")

hello